### ISSUE TITLE
Issue with "bb theme-build --sourcemaps" is not working on Windows OS

### ISSUE THREAD

**Issue by popovski** [Backbase/bb-cli#143]
Steps to reproduce 
Execute the tool in the root theme folder
example path: "D:\dev\alder_new\statics\collection\collection-aldermore\theme-asset-finance"
Executing: "bb theme-build --sourcemaps"

Error log:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\utils\input-source-map-tracker.js:191:56
    at Array.forEach (native)
    at trackContentSources (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\utils\input-source-map-tracker.js:188:20)
    at InputSourceMapStore.trackLoaded (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\utils\input-source-map-tracker.js:255:3)
    at fromString (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\utils\input-source-map-tracker.js:32:8)
    at InputSourceMapStore.track (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\utils\input-source-map-tracker.js:236:5)
    at C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\clean.js:145:44
    at CleanCSS.minify (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\clean-css\lib\clean.js:127:42)
    at C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\gulp-minify-css\index.js:39:35
    at vinylBufferStream (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\vinyl-bufferstream\index.js:50:5)
    at Transform.modifyContents [as _transform] (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\gulp-minify-css\index.js:65:7)
    at Transform._read (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\gulp-minify-css\node_modules\readable-stream\lib\_stream_transform.js:172:10)

    at Transform._write (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\gulp-minify-css\node_modules\readable-stream\lib\_stream_transform.js:160:12
)
    at doWrite (C:\Users\nikola\AppData\Roaming\npm\node_modules\bb-cli\node_modules\gulp-minify-css\node_modules\readable-stream\lib\_stream_writable.js:333:12)

**Comment by tcorral** [comment]
Hi, @popovski  
I have tried to reproduce it in my Windows machine and I could not reproduce it.

What Node.js version have you installed?
What NPM version have you installed?
What's the Windows OS version?

Could you also send us the basic information of your computer?

I attach mine to explain what I mean.

![image](https://cloud.githubusercontent.com/assets/802081/15993963/67c68178-30f6-11e6-95d3-04639ecc659e.png)

That's my output, could you send us yours, please?
![image](https://cloud.githubusercontent.com/assets/802081/15993967/838d8dac-30f6-11e6-8068-ebb385464c82.png)

I will be waiting for read more about you and that issue to solve it ASAP.

**Comment by tcorral** [comment]
Anything new, @popovski ?
