### ISSUE TITLE
bb import-collection fails. EMFILE: too many open files,

### ISSUE THREAD

**Issue by Mukesh85** [Backbase/bb-cli#168]
Running bb import-collection throws me the following error. I'm running a windows 10, 64 bit machine.

 **EMFILE: too many open files**

Here's a stacktrace of the problem:

Unhandled rejection TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:540:11)
    at fs.writeFile (fs.js:1137:6)
    at go$writeFile (...\node_modules\bb-cli\node_modules\graceful-fs\graceful-fs.js:94:14)
    at Object.writeFile (...\node_modules\bb-cli\node_modules\graceful-fs\graceful-fs.js:91:12)
    at Object.tryCatcher (...\node_modules\bb-cli\node_modules\bluebird\js\main\util.js:26:23)
    at Object.ret [as writeFileAsync] (eval at <anonymous> (...\node_modules\bb-cli\node_modules\bluebird\js\main\promisify.js:163:12), <anonymous>:14:23)
    at ZipDir._.assign.writeZip (...\node_modules\bb-cli\lib\zipDir.js:40:19)
    at ...\node_modules\bb-cli\lib\zipDir.js:32:32
    at _fileCreated (...\node_modules\bb-cli\node_modules\tmp\lib\tmp.js:222:23)
    at FSReqWrap.oncomplete (fs.js:82:15)

I'm using bb-cli version 0.4.0

**Comment by redaHamioui** [comment]
i get the same issue but when i repeat the command many time at least 5 times it's wrks fine

**Comment by Mukesh85** [comment]
Solved it by removing half the components from bower.json and importing them separately.
